language: bash
sudo: required
os:
  - linux
before_install:
  - echo "Before Install scripts Start"
  - sudo apt-get update -qq
install:
  - echo "Install scripts Starting"
  - ./build/install.sh
script:
  - echo "shell commands Starting"
  - ./build/build.sh
after_success:
  - echo "PASSED!"
after_failure:
  - echo "FAILURE IS ALWAYS AN OPTION"
after_script:
  - echo "more shell commands here"
notifications:
  email: false
env:
  - NODE_ENV=production
  - NODE_ENV=staging
