dist: trusty
language: sh
before_script:
- sudo add-apt-repository -y "deb http://mirrors.kernel.org/ubuntu trusty main universe"
- sudo apt-get -y update
- sudo apt-get -y install shellcheck

before_install:
- echo "Before Install scripts Start\n NODE ENV:"
- echo $NODE_ENV
- echo "Decrypting Environmentals"
- openssl aes-256-cbc -K $encrypted_1c676f2c50bd_key -iv $encrypted_1c676f2c50bd_iv -in ".travis/TRACE.enc" -out TRACE -d
install:
- echo "Install scripts Starting"
script:
- echo "shell commands Starting"
- bash -c 'shopt -s globstar; shellcheck **/*.{sh,bash}'
after_success:
- echo "PASSED!"
- pwd
- '$(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" --iv "$encrypted_XXXXXXXXXXXX_iv" --path-encrypted-key ".travis/TRACE.enc"'
after_failure:
- echo "FAILURE IS ALWAYS AN OPTION"
after_script:
- echo "more shell commands here"
notifications:
    email: false
env:
    global:
    - secure: bdjiE4zYXJWSrfO1TdjGZ0cVKepaOzzk7a5wrywdrKstDm5fmZi1rfGbzrXwfPhFYSoJNf/1KgfwWFZvb1EsLYigYb0pe2TdWHPQqshO7k5Ahl5e1ryJeKtl8YKRzK5nWrkP5ubzShgzen5Zlei3+WYxCXY6Z2UHdEvLXbcqhiiySY7/byxUwDdqGPu9pMOAqBDo8OBNe3L5LwjAENEVqx1yYqPrzWXJUw/JFUevBZ107ezdduyBtidPLWxV9flZs7I/tmVNXaB9+mvYGPelUpelSggtZOEoW1kmkCnRKpq2Z13zkJfW7XL3rmwlz78GwDbLfMiE6hhNyU6XoGrn8hoPicj6iGjVbxYXNechPABJPsSIgTmH38zCSD1y0Nx7iC1oagdYkQo2HWlGVFVDfBJaE5B8Av7A74RZpWdTbe1LHB8PtBB5HMJpCwRG7qjwX/zedp0/01IIt0IAQyaI7gZfSlYIoBKjDzFMuUHUs4MnfnvbPawcSWsp54Fvp3Hfl3BUsI56fmZTb6PlqgwfrwhvkZvDTv2rTCpY/SGr5EqKdC1J6FtLeTvzB56K4iySHijSHK9sFvPWOPVI8rYunWUbne0Ulk6eKyjNFhr4GSooatNuOWT8mkqBudMSvEA47sV/AerbbFrH9btELLkZZ/AdEmCpaFbzBd+pzcVhWHw=
    - secure: iM1CUVZWF9QToXvclGPuSFWyAEabHXVoYAEXAnGuyBqdakGXXmx0BuFjFwYgcNhq6qzlSbPwjvEbJM0iQGzpsy+n3IjLmSVq0tTpqU4LuG6GIKzlj0iMcEORXJ9XEoBNp7n9Xk+sDVqQwXooFqySQHVzoBVS8jQKYomVN3tL0FC/IxbDrrl/hdC5laZEYz1iNXXUcjatrVRnpgL5E2GfvgTKvwoUPapKfKUbo7B8AX7fiVht26CqEPrB4JMjlt4hkqY6IZjX9C8LZHMSchetwsku1qHGVb0hX0UndmcYFZu7/zBGgLZryHnQsjL/2NoqjwTLu51JuK2mrjkewfb9hzsb94uciz3t9ErMklN4cvPcZdbrg+grRWii3J6b9lWJTB9vQRYxwFKeoqBEPQZ6eiwEVQHkDExXMnZsP2NOzk1e8xaUtyPAeafuQvD46RC/OFnMRmw6BgH1312ZV8V3Z6qAun86MiC9CULmLltduNh9oLoODsaDg3MaVr2eQYVDC/uyCAl/GXa1xaMj5Un2rUruevarMXMS9kLtQMcagSU6BRB8exEGsNVgMhqPEnL3mwXMfQXuZGIiv4ypKnopN5IVsq8FpDYNEYArGRVxEz2/OZexp6Kj1Oh9E5yrkStbjXVIgDFIVj9A7uKWS+iOHmUb34Fy8AP/Cfp1Q/MFPuY=
    - secure: r1mOuNCmLLOtAV3gOS4pwGAtjvx736BrRnkYmMWW8QkDAS+GiaErB/kafX6XjoIpGcYJ9wjViLN6qKOha1m8rMPtjRMKfIwU4R5VvyiESralHwbI91JDjfnf9QQc66Vqeh1LtdL0x8HScTEmj8Vdyx9Y63vI5PEam2uio3lxUsSUGw1eA5hAs80bKMMWVORpToTWIwpuvgvrf5g2XbMbJmhmBmp7sDz8uiteHxmJVT8hDLoKZ+udz03pXR0e74HgpWYdrzpJ1NNDiJYVXc+scD9flHvaH9oy+/NwnawoBdM3H1BYo9RewIFCUP0a5Gyaj2nHXGZPtZI/I1JNLNiiIe3NChh8cMOn/wJM6OdHi1wdmLL3u1WiCVcr6V2u+RtVl9ySvC7yAiW82kw3rNRODTnpNvaXobA6TTyW+/8vxP2AQ86IYqA4Re7wMYZ2fPuLm1IbPKK94rukPdx6ZaaY0aXMjfTOLL42UT30SZc8IOC+K9ZDxTse7Gohm1pa5ZBmKieyuDb0q3xXmnMZSaqOnq7/qF9Ru8z29PNsxGEZmpMV1qZaxQVPhs9W3o1ESo9On08xYOMCyc2lsMO1rR3rGx5jv91LTbfZ2P3IigfSuK8A9UXkDoXeYsgxXWBladdlycKsdaURPeCvqdGwAk5QOaIWHgouUKxJPveqRfR10FI=
